/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Controler;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.*;
import model.Mensagem;
import model.Mensagem.Acao;

/**
 *
 * @author Michael
 */
public class ClienteFrame extends javax.swing.JFrame {

  
    public ClienteFrame() {
        initComponents();

    }

    private void botoes(boolean conectar, boolean limpar, boolean enviar) {
        this.btn_conectar.setEnabled(conectar);
        this.btn_enviar.setEnabled(enviar);
        this.btn_limpar.setEnabled(limpar);
    }

    private void caixaTextos(boolean nome, boolean mensagem, boolean historico) {
        this.txt_nome.setEditable(nome);
        this.txt_mensagem.setEnabled(mensagem);
        this.txt_historico.setEnabled(historico);
    }

    private void limpaTextos() {
        this.txt_nome.setText("");
        this.txt_historico.setText("");
        this.txt_mensagem.setText("");
    }

    private void novaNoticia(String texto, int tipo) {
        JOptionPane.showMessageDialog(this, texto, getTitle(), tipo);
    }

    public void conectou(boolean taConectado) {
        if (taConectado) {
            botoes(false, true, true);
            caixaTextos(false, true, true);

            novaNoticia("Você se juntou a sala", JOptionPane.PLAIN_MESSAGE);
        } else {
            limpaTextos();
            novaNoticia("Conexão não realizada!\nTente novamente com um novo nome.", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void recebeMensagem(Mensagem mensagem) {
        this.txt_historico.append(mensagem.getOrigem() + " diz: " + mensagem.getConteudo() + "\n");
    }

    public void recebeSussurro(Mensagem message) {
        this.txt_historico.append(message.getOrigem() + " sussurrou: " + message.getConteudo() + "\n");
    }

    public void atualizaListaOnline(String[] array) {
        this.lista_de_online.setListData(array);
        this.lista_de_online.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.lista_de_online.setLayoutOrientation(JList.VERTICAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_de_online = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_historico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_mensagem = new javax.swing.JTextArea();
        btn_enviar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        btn_conectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoas Online"));

        jScrollPane3.setViewportView(lista_de_online);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt_historico.setEditable(false);
        txt_historico.setColumns(20);
        txt_historico.setRows(5);
        txt_historico.setEnabled(false);
        jScrollPane1.setViewportView(txt_historico);

        txt_mensagem.setColumns(20);
        txt_mensagem.setRows(5);
        txt_mensagem.setEnabled(false);
        txt_mensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_mensagemKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txt_mensagem);

        btn_enviar.setText("Enviar");
        btn_enviar.setEnabled(false);
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.setEnabled(false);
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_enviar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enviar)
                    .addComponent(btn_limpar)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Conectar"));

        btn_conectar.setText("Connectar");
        btn_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_conectar))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_conectar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        this.txt_mensagem.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        enviaMensagem();
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conectarActionPerformed
        String nome = this.txt_nome.getText();
        if (!nome.isEmpty()) {
            Mensagem mensagem = new Mensagem();
            mensagem.setAcao(Acao.CONECTAR);
            mensagem.setOrigem(nome);
            Controler.getInstance().conectar(mensagem);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btn_conectarActionPerformed

    private void txt_mensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mensagemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            enviaMensagem();
        } else {
            System.out.println(evt.getKeyCode() + " - " + evt.isActionKey());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mensagemKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        Mensagem msg = new Mensagem();
        msg.setAcao(Acao.DESCONECTAR);
        msg.setOrigem(txt_nome.getText());
        Controler.getInstance().desconectar(msg);

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void enviaMensagem() {
        String conteudoMensagem = this.txt_mensagem.getText().trim();
        String origemMensagem = txt_nome.getText();

        Mensagem mensagem = new Mensagem();

        if (this.lista_de_online.getSelectedIndex() > -1) {
            mensagem.setNomeReservado((String) this.lista_de_online.getSelectedValue());
            mensagem.setAcao(Acao.SUSSURRAR);
            lista_de_online.clearSelection();
        } else {
            mensagem.setAcao(Acao.ENVIAR);
        }

        if (!conteudoMensagem.isEmpty()) {
            mensagem.setOrigem(origemMensagem);
            mensagem.setConteudo(conteudoMensagem);

            this.txt_historico.append("Você disse: " + conteudoMensagem + "\n");

            Controler.getInstance().enviar(mensagem);
        }

        this.txt_mensagem.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conectar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lista_de_online;
    private javax.swing.JTextArea txt_historico;
    private javax.swing.JTextArea txt_mensagem;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
